// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'header': string;
  'item': string;
  'side': string;
}
export const cssExports: CssExports;
export default cssExports;
