// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar': string;
  'body': string;
  'context': string;
  'header': string;
  'side': string;
}
export const cssExports: CssExports;
export default cssExports;
